-- MySQL Script generated by MySQL Workbench
-- Rab 06 Apr 2022 05:50:39 
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema BTS_DATA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BTS_DATA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BTS_DATA` ;
USE `BTS_DATA` ;

-- -----------------------------------------------------
-- Table `BTS_DATA`.`ADMIN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BTS_DATA`.`ADMIN` (
  `Id_Admin` VARCHAR(10) NOT NULL,
  `Nama_Admin` VARCHAR(100) NULL DEFAULT NULL,
  `Email_Admin` NVARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Admin`));


-- -----------------------------------------------------
-- Table `BTS_DATA`.`SURVEYOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BTS_DATA`.`SURVEYOR` (
  `Id_Surveyor` VARCHAR(10) NOT NULL,
  `Nama_Surveyor` VARCHAR(100) NULL DEFAULT NULL,
  `Email_Surveyor` NVARCHAR(100) NULL DEFAULT NULL,
  `Riwayat_Survey` NVARCHAR(255) NULL DEFAULT NULL,
  `Jumlah_Survey` INT NULL DEFAULT NULL,
  `Id_Pembuat_Data` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Id_Surveyor`),
  INDEX (`Id_Pembuat_Data` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`Id_Pembuat_Data`)
    REFERENCES `BTS_DATA`.`ADMIN` (`Id_Admin`));


-- -----------------------------------------------------
-- Table `BTS_DATA`.`KUESIONER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BTS_DATA`.`KUESIONER` (
  `Id_Kuesioner` VARCHAR(30) NOT NULL,
  `Topik_Kuesioner` NVARCHAR(255) NULL DEFAULT NULL,
  `Deskripsi_Kuesioner` TEXT NULL DEFAULT NULL,
  `Waktu_Dibuat` DATETIME NULL DEFAULT NULL,
  `Id_Pembuat` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Id_Kuesioner`),
  INDEX (`Id_Pembuat` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`Id_Pembuat`)
    REFERENCES `BTS_DATA`.`ADMIN` (`Id_Admin`));


-- -----------------------------------------------------
-- Table `BTS_DATA`.`PERTANYAAN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BTS_DATA`.`PERTANYAAN` (
  `Id_Pertanyaan` VARCHAR(30) NOT NULL,
  `Isi_Pertanyaan` TEXT NULL DEFAULT NULL,
  `Id_Kuesioner` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Id_Pertanyaan`),
  INDEX (`Id_Kuesioner` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`Id_Kuesioner`)
    REFERENCES `BTS_DATA`.`KUESIONER` (`Id_Kuesioner`));


-- -----------------------------------------------------
-- Table `BTS_DATA`.`PILIHAN_JAWABAN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BTS_DATA`.`PILIHAN_JAWABAN` (
  `Id_Pil_Jwb` VARCHAR(30) NOT NULL,
  `Pilihan_Jawaban` TEXT NULL DEFAULT NULL,
  `Id_Kuesioner` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Id_Pil_Jwb`),
  INDEX (`Id_Kuesioner` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`Id_Kuesioner`)
    REFERENCES `BTS_DATA`.`KUESIONER` (`Id_Kuesioner`));


-- -----------------------------------------------------
-- Table `BTS_DATA`.`LOGIN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BTS_DATA`.`LOGIN` (
  `Id_Log` VARCHAR(30) NOT NULL,
  `Waktu_Login` DATETIME NOT NULL,
  `Id_Admin` VARCHAR(10) NULL DEFAULT NULL,
  `Id_Surveyor` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Log`),
  INDEX (`Id_Admin` ASC) VISIBLE,
  INDEX (`Id_Surveyor` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`Id_Admin`)
    REFERENCES `BTS_DATA`.`ADMIN` (`Id_Admin`),
  CONSTRAINT ``
    FOREIGN KEY (`Id_Surveyor`)
    REFERENCES `BTS_DATA`.`SURVEYOR` (`Id_Surveyor`));


-- -----------------------------------------------------
-- Table `BTS_DATA`.`PASSWORD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BTS_DATA`.`PASSWORD` (
  `Id_Password` VARCHAR(30) NOT NULL,
  `Password` NVARCHAR(30) NOT NULL,
  `Id_Admin` VARCHAR(10) NULL DEFAULT NULL,
  `Id_Surveyor` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Password`),
  INDEX (`Id_Admin` ASC) VISIBLE,
  INDEX (`Id_Surveyor` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`Id_Admin`)
    REFERENCES `BTS_DATA`.`ADMIN` (`Id_Admin`),
  CONSTRAINT ``
    FOREIGN KEY (`Id_Surveyor`)
    REFERENCES `BTS_DATA`.`SURVEYOR` (`Id_Surveyor`));


-- -----------------------------------------------------
-- Table `BTS_DATA`.`JENIS_BTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BTS_DATA`.`JENIS_BTS` (
  `Id_Jenis_BTS` TINYINT NOT NULL,
  `Jenis_BTS` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Jenis_BTS`));


-- -----------------------------------------------------
-- Table `BTS_DATA`.`PEMILIK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BTS_DATA`.`PEMILIK` (
  `Id_Pemilik` VARCHAR(10) NOT NULL,
  `Nama_Pemilik` VARCHAR(255) NULL DEFAULT NULL,
  `Alamat_Pemilik` TEXT NULL DEFAULT NULL,
  `NoTelp_Pemilik` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Pemilik`));


-- -----------------------------------------------------
-- Table `BTS_DATA`.`PARENT_WILAYAH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BTS_DATA`.`PARENT_WILAYAH` (
  `Id_Parent` INT NOT NULL,
  `Nama_Kecamatan` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Parent`));


-- -----------------------------------------------------
-- Table `BTS_DATA`.`WILAYAH`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BTS_DATA`.`WILAYAH` (
  `Id_Wilayah` INT NOT NULL,
  `Nama_Wilayah` TEXT NULL DEFAULT NULL,
  `Level_Wilayah` INT NULL DEFAULT NULL,
  `Id_Parent_Wilayah` INT NOT NULL,
  PRIMARY KEY (`Id_Wilayah`),
  INDEX (`Id_Parent_Wilayah` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`Id_Parent_Wilayah`)
    REFERENCES `BTS_DATA`.`PARENT_WILAYAH` (`Id_Parent`));


-- -----------------------------------------------------
-- Table `BTS_DATA`.`INFO_BTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BTS_DATA`.`INFO_BTS` (
  `Id_BTS` VARCHAR(5) NOT NULL,
  `Id_Jenis_BTS` TINYINT NOT NULL,
  `Nama_BTS` VARCHAR(100) NULL DEFAULT NULL,
  `Lokasi_BTS` NVARCHAR(255) NULL DEFAULT NULL,
  `Panjang_Tanah` FLOAT(6,2) NULL DEFAULT NULL,
  `Lebar_Tanah` FLOAT(6,2) NULL DEFAULT NULL,
  `Latitude` FLOAT(10,6) NULL DEFAULT NULL,
  `Longitude` FLOAT(11,6) NULL DEFAULT NULL,
  `Tinggi_Tower` FLOAT(6,2) NULL DEFAULT NULL,
  `Ada_Genset` TINYINT NULL DEFAULT NULL,
  `Ada_Tembok_Batas` TINYINT NULL DEFAULT NULL,
  `Waktu_Dibuat_Info` DATETIME NULL DEFAULT NULL,
  `Id_Pemilik_BTS` VARCHAR(10) NOT NULL,
  `Id_Pembuat_Info` VARCHAR(10) NOT NULL,
  `Id_Wilayah` INT NOT NULL,
  PRIMARY KEY (`Id_BTS`),
  INDEX (`Id_Pemilik_BTS` ASC) VISIBLE,
  INDEX (`Id_Pembuat_Info` ASC) VISIBLE,
  INDEX (`Id_Wilayah` ASC) VISIBLE,
  INDEX (`Id_Jenis_BTS` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`Id_Pemilik_BTS`)
    REFERENCES `BTS_DATA`.`PEMILIK` (`Id_Pemilik`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT ``
    FOREIGN KEY (`Id_Pembuat_Info`)
    REFERENCES `BTS_DATA`.`ADMIN` (`Id_Admin`),
  CONSTRAINT ``
    FOREIGN KEY (`Id_Wilayah`)
    REFERENCES `BTS_DATA`.`WILAYAH` (`Id_Wilayah`),
  CONSTRAINT ``
    FOREIGN KEY (`Id_Jenis_BTS`)
    REFERENCES `BTS_DATA`.`JENIS_BTS` (`Id_Jenis_BTS`));


-- -----------------------------------------------------
-- Table `BTS_DATA`.`BTS_FOTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BTS_DATA`.`BTS_FOTO` (
  `Id_Foto_BTS` INT NOT NULL AUTO_INCREMENT,
  `Path_Foto` TEXT NULL DEFAULT NULL,
  `Id_BTS` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`Id_Foto_BTS`),
  INDEX (`Id_BTS` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`Id_BTS`)
    REFERENCES `BTS_DATA`.`INFO_BTS` (`Id_BTS`));


-- -----------------------------------------------------
-- Table `BTS_DATA`.`MONITORING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BTS_DATA`.`MONITORING` (
  `Id_Monitoring` VARCHAR(20) NOT NULL,
  `Tahun_Monitoring` YEAR NULL DEFAULT NULL,
  `Waktu_Generate` DATETIME NULL DEFAULT NULL,
  `Waktu_Kunjungan` DATETIME NULL DEFAULT NULL,
  `Id_BTS` VARCHAR(5) NOT NULL,
  `Id_Surveyor` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Id_Monitoring`),
  INDEX (`Id_BTS` ASC) VISIBLE,
  INDEX (`Id_Surveyor` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`Id_BTS`)
    REFERENCES `BTS_DATA`.`INFO_BTS` (`Id_BTS`),
  CONSTRAINT ``
    FOREIGN KEY (`Id_Surveyor`)
    REFERENCES `BTS_DATA`.`SURVEYOR` (`Id_Surveyor`));


-- -----------------------------------------------------
-- Table `BTS_DATA`.`JAWABAN_KUESIONER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BTS_DATA`.`JAWABAN_KUESIONER` (
  `Id_Jawaban` VARCHAR(10) NOT NULL,
  `Jawaban_Kuesioner` INT NULL DEFAULT NULL,
  `Waktu_Buat` DATETIME NULL DEFAULT NULL,
  `Id_Kuesioner` VARCHAR(30) NOT NULL,
  `Id_Surveyor` VARCHAR(10) NOT NULL,
  `Id_Monitoring` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Id_Jawaban`),
  INDEX (`Id_Kuesioner` ASC) VISIBLE,
  INDEX (`Id_Surveyor` ASC) VISIBLE,
  INDEX (`Id_Monitoring` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`Id_Kuesioner`)
    REFERENCES `BTS_DATA`.`KUESIONER` (`Id_Kuesioner`),
  CONSTRAINT ``
    FOREIGN KEY (`Id_Surveyor`)
    REFERENCES `BTS_DATA`.`SURVEYOR` (`Id_Surveyor`),
  CONSTRAINT ``
    FOREIGN KEY (`Id_Monitoring`)
    REFERENCES `BTS_DATA`.`MONITORING` (`Id_Monitoring`));


-- -----------------------------------------------------
-- Table `BTS_DATA`.`EDIT_KUESIONER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BTS_DATA`.`EDIT_KUESIONER` (
  `Waktu_Diedit` DATETIME NOT NULL,
  `Id_Editor` VARCHAR(10) NOT NULL,
  `Id_Kuesioner` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Waktu_Diedit`),
  INDEX (`Id_Editor` ASC) VISIBLE,
  INDEX (`Id_Kuesioner` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`Id_Editor`)
    REFERENCES `BTS_DATA`.`ADMIN` (`Id_Admin`),
  CONSTRAINT ``
    FOREIGN KEY (`Id_Kuesioner`)
    REFERENCES `BTS_DATA`.`KUESIONER` (`Id_Kuesioner`));


-- -----------------------------------------------------
-- Table `BTS_DATA`.`EDIT_JAWABAN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BTS_DATA`.`EDIT_JAWABAN` (
  `Waktu_Diedit` DATETIME NOT NULL,
  `Id_Editor` VARCHAR(10) NOT NULL,
  `Id_Jawaban_Diedit` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Waktu_Diedit`),
  INDEX (`Id_Editor` ASC) VISIBLE,
  INDEX (`Id_Jawaban_Diedit` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`Id_Editor`)
    REFERENCES `BTS_DATA`.`SURVEYOR` (`Id_Surveyor`),
  CONSTRAINT ``
    FOREIGN KEY (`Id_Jawaban_Diedit`)
    REFERENCES `BTS_DATA`.`JAWABAN_KUESIONER` (`Id_Jawaban`));


-- -----------------------------------------------------
-- Table `BTS_DATA`.`EDIT_INFO_BTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BTS_DATA`.`EDIT_INFO_BTS` (
  `Waktu_Diedit` DATETIME NOT NULL,
  `Id_Editor` VARCHAR(10) NOT NULL,
  `Id_BTS_edit` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`Waktu_Diedit`),
  INDEX (`Id_Editor` ASC) VISIBLE,
  INDEX (`Id_BTS_edit` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`Id_Editor`)
    REFERENCES `BTS_DATA`.`ADMIN` (`Id_Admin`),
  CONSTRAINT ``
    FOREIGN KEY (`Id_BTS_edit`)
    REFERENCES `BTS_DATA`.`INFO_BTS` (`Id_BTS`));


-- -----------------------------------------------------
-- Table `BTS_DATA`.`KONFIGURASI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BTS_DATA`.`KONFIGURASI` (
  `Id_Konfigurasi` INT NOT NULL AUTO_INCREMENT,
  `Nama_Konfigurasi` NVARCHAR(20) NULL DEFAULT NULL,
  `Value_Konfigurasi` NVARCHAR(50) NULL DEFAULT NULL,
  `Waktu_Dibuat_Konfigurasi` DATETIME NOT NULL,
  `Waktu_Diedit_Konfigurasi` DATETIME NULL DEFAULT NULL,
  `Nama_Pembuat` VARCHAR(100) NULL DEFAULT NULL,
  `Nama_Pengedit_Konfigurasi` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Konfigurasi`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
